version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: bash -c "bin/delayed_job start && bin/rails s -b 0.0.0.0 -p 3000"
    env_file: .env
    environment:
      RAILS_MAX_THREADS: 5
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    build: ./docker/db
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=ja_JP.UTF-8'
    ports:
      - '15432:5432'
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
volumes:
  bundle:
    driver: local
